sudo docker-compose run app sh -c "django-admin.py startproject app ."
sudo docker-compose run app sh -c "python manage.py test"
sudo docker-compose run app sh -c "python manage.py test && flake8"
sudo docker-compose run app sh -c "python manage.py startapp core"
sudo docker-compose run app sh -c "python manage.py makemigrations core"
